### ISSUE TITLE
点击上传后，进入相册不选择图片退出，无法进入相册

### ISSUE THREAD

**Issue by liang7hi** [big-sponge/js-image-base64#2]

**Comment by big-sponge** [comment]
@liangqi0 
代码贴上来看看吧，  ios、安卓都无法重现

**Comment by liang7hi** [comment]
html:

<div class="img_block">
     <input type="file" name="2"  id="file-up" class="upload_img" style="display:none"  onchange = 'fileUp(this)'>
               
     <img id="boximg" src="./img/shangchuantupian.png" alt="" onclick="document.getElementById('file-up').click();"  />
               
 </div>







js:

var fileUp = function (me) {
                                base64Image({
                                    file: me,                              
                                    callback: function (baseStr) {       
                                        var imgs = '<p class="imgarr"><img src="'+baseStr+'"/><span></span></p>';
                                     
                                        if($(".imgarr").length < 3){
                                
                                            $(imgs).prependTo('.img_block');
                                
                                            $('.imgarr span').on('tap',function(){
                                                  $(this).parents('.imgarr').remove();
                                            })

                                        }else{
                                            $(this).remove();
                                            // $("#boximg").hide();

                                        };
                                        console.log(baseStr.length);
                                
                                        
                                    },
                                        width:750,                          
                                        ratio:0.75,                      
                                });

                            }

**Comment by big-sponge** [comment]
@liangqi0 
示例 中的代码存在这个问题吗？ 

http://www.tkc8.com/test/pic/index.html

**Comment by liang7hi** [comment]
没有

**Comment by liangqi0** [comment]
您q多少

**Comment by big-sponge** [comment]
1796512918 @liangqi0
